# Generated by Django 4.0.3 on 2024-12-13 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
    ]
